apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea
  name: gitea

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea
  name: gitea-cm

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea
  name: gitea-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: gitea
        app.kubernetes.io/instance: gitea
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 82
        fsGroup: 82
      initContainers:
      - name: init
        image: quay.io/simbelmas/alpine-tools:latest
        command: ["gitea-init.sh"]
        volumeMounts:
        - name: gitea-conf
          mountPath: /mnt
        - name: gitea-init
          mountPath: /usr/local/bin
        - name: app-data
          mountPath: /app
      containers:
      - name: gitea
        image: quay.io/simbelmas/gitea:latest
        volumeMounts:
        - name: app-data
          mountPath: /var/lib/gitea
        ports:
          - containerPort: 8080
          - containerPort: 8022
      volumes:
      - name: gitea-conf
        secret:
          defaultMode: 0640
          secretName: gitea-app-ini
      - name: gitea-init
        configMap:
          defaultMode: 0755
          name: gitea-cm
          items:
          - key: gitea-init.sh
            path: gitea-init.sh
      - name: app-data
        persistentVolumeClaim:
          claimName: gitea-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea
spec:
  ports:
  - name: gitea-http
    port: 8080
    protocol: TCP
  - name: gitea-ssh
    port: 8022
    protocol: TCP
  selector:
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/instance: gitea

---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-app-ini
