apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea

commonLabels:
  app.kubernetes.io/part-of: gitea

resources:
- gitea.yaml

configMapGenerator:
  - name: gitea-cm
    files:
      - config/gitea-init.sh
    behavior: merge

# Sample app.ini secret generation
#secretGenerator:
#  - name: gitea-app-ini
#    files:
#    - config/app.ini
#    behavior: merge